// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

const schema = "prisma/schema.prisma";
const migrations = { path: "prisma/migrations" };
const datasource = { url: process.env.DATABASE_URL ?? "" };

export default {
  schema,
  migrations,
  datasource,
};
